version: 2
orbs:
  win: circleci/windows@1.0.0
jobs:
  build:
    macos:
      xcode: "8.3.3"
    docker:
      - image: ubuntu:bionic
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./mach bootstrap

      - run:
          name: Configure
          command: ./mach configure

      - run:
          name: Build
          command: ./mach build


