version: 2
orbs:
  win: circleci/windows@1.0.0
executors:
  linux_docker_executor:
    docker:
      - image: ubuntu:bionic
  macosx_executor:
    macos:
      xcode: "8.3.3"
  windows_executor:
      name: win/vs2019
      shell: powershell.exe

jobs:
  macosx_build_job:
    executor: macosx_executor
    parallelism: 4
    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./mach bootstrap

      - run:
          name: Configure
          command: ./mach configure

      - run:
          name: Build
          command: ./mach build

  linux_build_job:
    executor: linux_docker_executor
    parallelism: 4
    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./mach bootstrap

      - run:
          name: Configure
          command: ./mach configure

      - run:
          name: Build
          command: ./mach build

  windows_build_job:
    executor: linux_docker_executor
    parallelism: 4
    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./mach bootstrap

      - run:
          name: Configure
          command: ./mach configure

      - run:
          name: Build
          command: ./mach build


